version: "3"

services:
  studipdownloader:
      image: studipdownloader
      build: 
        context: ../
        dockerfile: StudIPDownloader.WebApi/Dockerfile        
      ports:
         - "5000:5000"
         - "5001:5001"
      environment:
        - PORT=5000
        - HTTPS_PORT=5001
#          insert your own
        - STUDIP_URL=$STUDIP_URL
        - STUDIP_PASSWORD=$STUDIP_PASSWORD
        - STUDIP_USERNAME=$STUDIP_USERNAME
        - TIMER=60
          